### ISSUE TITLE
upstream must be defined before to run "git push upstream master --follow-tags"

### ISSUE THREAD

**Issue by alixdamman** [larray-project/releaser#14]
Using 
```bash
git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
```

See https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by alixdamman** [comment]
@gdementen you didn't encounter such problem during the last release?

**Comment by gdementen** [comment]
I don't remember anything about this during release. I do have an upstream remote defined in my local copy, but I would think you have too!?! I do it systematically for all my forks.

**Comment by alixdamman** [comment]
but the cleanup function remove everything, no?

**Comment by gdementen** [comment]
it should, unless the program crashed :)

**Comment by alixdamman** [comment]
meaning I need to reset ``upstream`` each time.

**Comment by gdementen** [comment]
I don't remember. Now that you say it, there was something I had to do manually for the last release, maybe it was that last "push upstream".

**Comment by gdementen** [comment]
obsolete by PR #32
